from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from .config_store import format_mac, normalize_mac

DERIVED_CREDENTIAL_KINDS = ("all", "hg5143f-telnet", "hg5143f-su")
HG5143F_TELNET_USERNAME = "telnetadmin"
HG5143F_TELNET_PASSWORD_PREFIX = "FH-nE7jA%5m"
HG5143F_SU_PASSWORD_PREFIX = "Fh@"


@dataclass(frozen=True)
class DerivedCredential:
    kind: str
    username: str
    password: str
    source: str
    mac: str
    mac_suffix: str
    persistent: bool
    note: str
    target: str
    confidence: str
    integration_level: str

    def render(self, *, reveal_secrets: bool = False) -> dict[str, Any]:
        return {
            "kind": self.kind,
            "target": self.target,
            "username": self.username,
            "password": self.password if reveal_secrets else "[REDACTED]",
            "redacted": not reveal_secrets,
            "source": self.source,
            "mac": format_mac(self.mac),
            "mac_suffix": self.mac_suffix,
            "persistent": self.persistent,
            "confidence": self.confidence,
            "integration_level": self.integration_level,
            "note": self.note,
        }


def mac_suffix(mac: str) -> str:
    return normalize_mac(mac)[-6:]


def derive_hg5143f_telnet(mac: str) -> DerivedCredential:
    normalized = normalize_mac(mac)
    suffix = mac_suffix(normalized)
    return DerivedCredential(
        kind="hg5143f-telnet",
        username=HG5143F_TELNET_USERNAME,
        password=f"{HG5143F_TELNET_PASSWORD_PREFIX}{suffix}",
        source="HG5143F telnetadmin formula: fixed prefix + MAC suffix",
        mac=normalized,
        mac_suffix=suffix,
        persistent=True,
        target="telnet-login",
        confidence="high-hg5143f-local-live-verified",
        integration_level="automatic-telnet-fallback",
        note=(
            "Default Telnet login credential observed on HG5143F V4 firmware. "
            "Explicit CLI username/password still override it."
        ),
    )


def derive_hg5143f_su(mac: str) -> DerivedCredential:
    normalized = normalize_mac(mac)
    suffix = mac_suffix(normalized)
    return DerivedCredential(
        kind="hg5143f-su",
        username="root",
        password=f"{HG5143F_SU_PASSWORD_PREFIX}{suffix}",
        source="HG5143F serviceMgr runtime formula: fixed prefix + brmac suffix",
        mac=normalized,
        mac_suffix=suffix,
        persistent=False,
        target="su-root-runtime",
        confidence="high-hg5143f-local-live-verified",
        integration_level="derive-display-only",
        note=(
            "Runtime su credential generated by serviceMgr into /var/telsu; "
            "it is not a clean persistent data-model password."
        ),
    )


def derive_credentials(mac: str, kind: str) -> list[DerivedCredential]:
    if kind == "all":
        return [derive_hg5143f_telnet(mac), derive_hg5143f_su(mac)]
    if kind == "hg5143f-telnet":
        return [derive_hg5143f_telnet(mac)]
    if kind == "hg5143f-su":
        return [derive_hg5143f_su(mac)]
    raise ValueError(f"unsupported credential kind: {kind}")
